# espkyogate - ESPHome custom component for Bentel KYO alarms (https://github.com/lorenzo-deluca/espkyogate)
# 2025 Lorenzo De Luca (me@lorenzodeluca.dev)
# Example YAML for Bentel Kyo32-32G-8W-8WG

external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]

esp8266:
  board: d1_mini
  restore_from_flash: true

esphome:
  name: espkyogate
  friendly_name: espkyogate
  includes:
    - components/bentel-kyo/bentel_kyo32.h

uart:
  id: uart_bus
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600
  data_bits: 8
  parity: EVEN  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  ap:
    ssid: "Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_encryption_key
  custom_services: true

ota:
  - platform: esphome
    password: !secret ota_password
  
switch:
  - platform: safe_mode
    name: "ESPKyoGate (Safe Mode)"

binary_sensor:
  - platform: custom
    lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return {
        kyo32->kyo_comunication,
        kyo32->stato_sirena,
        kyo32->warn_batteria_bassa,
        &kyo32->allarme_area[0],
        &kyo32->zona[0], 
        &kyo32->zona[1],
        &kyo32->zona[2], 
        &kyo32->zona[3]
      };
    binary_sensors:
      - id: kyo_comunication
        name: "Communication centrale"
      - id: stato_sirena
        name: "Etat sirene"
      - id: warn_batteria_bassa
        name: "Batterie faible"
      - id: allarme_area_1
        name: "Alarme générale"
      - id: kyo_zone1
        name: "Cuisine"
        device_class: "door"
      - id: kyo_zone2
        name: "Entree"
        device_class: "door"
      - id: kyo_zone3
        name: "Couloir"
        device_class: "motion"
      - id: kyo_zone4
        name: "Salon"
        device_class: "motion"

sensor:
  - platform: uptime
    name: "Uptime Sensor"
  - platform: wifi_signal
    name: "WiFi Signal"

text_sensor:
  - platform: version
    name: "ESPHome Version"
